# Generated by Django 5.2.17 on 2026-10-05 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('starts_at', models.DateTimeField(verbose_name='Начало')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('format', models.CharField(max_length=150, verbose_name='Формат')),
                ('speakers', models.TextField(blank=True, help_text='Один спикер на строку', verbose_name='Спикеры')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('registration_url', models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Ссылка на регистрацию')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Место')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'мероприятия',
                'ordering': ['starts_at', 'pk'],
                'indexes': [models.Index(fields=['is_published', 'starts_at'], name='events_even_is_publ_415ff6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='event_end_after_start')],
            },
        ),
    ]
