# Generated by Django 5.2.17 on 2026-10-05 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('position', models.CharField(max_length=300, verbose_name='Должность')),
                ('bio', models.TextField(blank=True, help_text='1–3 предложения', verbose_name='Короткая биография')),
                ('website', models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'резидент',
                'verbose_name_plural': 'резиденты',
                'ordering': ['order', 'name', 'pk'],
            },
        ),
    ]
