# Generated by Django 5.2.17 on 2026-10-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_seed_residents'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='photo',
            field=models.ImageField(blank=True, help_text='JPEG, PNG или WebP до 5 МБ. Желательно портретное фото.', upload_to='residents/', verbose_name='Фото'),
        ),
    ]
